In [1]:
import tensorflow as tf

In [10]:
# x = tf.constant(4.0, shape=(1,1))
# x = tf.constant([[1,2,3], [4,5,6]])
# x = tf.ones((2,3)) # ones, zeros, eye for identity
# x = tf.random.normal((3,3), mean=0, stddev=1)
x= tf.range(9)
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8.], shape=(9,), dtype=float64)


In [13]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = x + y
z = tf.add(x,y)

# matrix multiply with tf.matmul() or @
# * is element-wise multiplication

print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [14]:
a = tf.range(9)
print(a)

a = tf.reshape(a, (3,3))
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
